apiVersion: v1
kind: Service
metadata:
   name: backend-service
   namespace: app-dev
spec:
   type: ClusterIP
   selector:
      app: backend
   ports:
      - name: http
        port: 8081
        targetPort: 8081
