apiVersion: v1
kind: Service
metadata:
   name: redis
   namespace: app-dev
spec:
   type: ClusterIP                # ClusterIP service to expose the redis-deployment to internal DNS
   selector:
      app: redis
   ports: 
      - port: 6379
